Repository Nookipedia/acnh.directory, pull requests merged in 2020-10, with the labels that each got.

#1 Listing Nook DB.io and AC Miles
  src/assets/data/projects.json
  src/assets/images/logos/nook-db-io.png
Labels: new listing

#9 change: switch to TS modules for data
  README.md
  src/app/data/archive.ts
  src/app/data/project-data.ts
  src/app/directory/directory.component.ts
  src/assets/data/archive.json
  src/assets/data/projects.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#10 Cleanup, git support, more projects
  src/app/data/languages.ts
  src/app/data/project-data.ts
  src/app/directory/directory.component.css
  src/app/directory/directory.component.html
  src/app/directory/directory.component.ts
  src/assets/images/links/git.png
Labels: enhancement, modify listing, new listing

#11 add: CatalogScanner git repo
  src/app/data/project-data.ts
Labels: modify listing

#12 Adding Twitter for Nooks Guide + consistent formatting
  src/app/data/project-data.ts
Labels: modify listing

#13 Decreasing logo sizes
  src/assets/images/logos/ac-helper.png
  src/assets/images/logos/acnh-database.png
  src/assets/images/logos/acw.png
  src/assets/images/logos/cestislife.png
  src/assets/images/logos/dodocodescom.png
  src/assets/images/logos/garden-science.png
  src/assets/images/logos/nooknet.png
  src/assets/images/logos/nooks-island.png
  src/assets/images/logos/stalks-io.png
  src/assets/images/logos/turnip-exchange.png
  src/assets/images/logos/yue's-acnh-guides.png
Labels: enhancement

#16 Updates to the build process
  .github/workflows/build.yml
  package.json
Labels: enhancement

#20 Update ACNH.Guide
  src/app/data/project-data.ts
  src/assets/images/logos/acnh-guide.gif
  src/assets/images/logos/acnh-guide.png
Labels: modify listing

#21 Update ACNH Travel Guide info & icon
  src/app/data/project-data.ts
  src/assets/images/logos/acnh-travel-guide.png
Labels: modify listing

#22 Links target="_blank" and cleanup.
  src/app/app.component.html
  src/app/directory/directory.component.html
  src/app/privacy/privacy.component.html
  src/assets/images/logos/acnh-guide.gif
  src/assets/images/logos/tanuki-forest.gif
Labels: enhancement
